# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Data_Wizard
                                 A QGIS plugin
 The Wizard creates input data for IB-Tool
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-01
        copyright            : (C) 2026 by Oliver Harig
        email                : ottmar.hittzfeld@web.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Data_Wizard class from file Data_Wizard.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .data_wizard import Data_Wizard
    return Data_Wizard(iface)
